version: '3.8'

services:
  web:
    build: .
    ports:
      - "8084:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - USE_MONGO=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 新增：容器退出就自动重启
    restart: always
    command: python manage.py runserver 0.0.0.0:8000