services:
  web:
    build: .             
    image: mysite   # the same name with docker build
    ports:
      - "82:82"
    volumes:
      - /usr/local/mysite:/usr/local/mysite
    environment:
      - PYTHONUNBUFFERED=1
