# Generated by Django 3.2.25 on 2025-01-01 15:38

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', djongo.models.fields.JSONField()),
                ('top', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('pathname', models.CharField(blank=True, max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('viewer', models.IntegerField(default=0)),
                ('visited', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('lastVisitedTime', models.DateTimeField()),
            ],
        ),
    ]
